name: Enter Reflections

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-complete:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run completeness check script
      run: |
        chmod +x ./.github/workflows/check-complete.sh
        bash ./.github/workflows/check-complete.sh
